### ISSUE TITLE
安装时报以下错误  tasks_control是什么模块没有找到

### ISSUE THREAD

**Issue by lyt1216** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-enhanced#4]
2024-03-03 20:38:29,478 [  Default][    ERROR] plugin load error(amiyabot-arknights-hsyhhssyy-enhanced-1.3.zip): Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/amiyabot/log/manager.py", line 159, in catch
    yield
  File "/root/Amiya-Bot/core/plugins/__init__.py", line 40, in load_plugin_file
    res = self.bot.load_plugin(file, extract_plugin=True)
  File "/usr/local/lib/python3.10/dist-packages/amiyabot/factory/__init__.py", line 257, in load_plugin
    module = import_module(os.path.basename(dest))
  File "/usr/local/lib/python3.10/dist-packages/amiyabot/util/systemUtils.py", line 56, in import_module
    return importlib.import_module(path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Amiya-Bot/plugins/amiyabot-arknights-hsyhhssyy-enhanced-1_3/__init__.py", line 1, in <module>
    from .main import bot
  File "/root/Amiya-Bot/plugins/amiyabot-arknights-hsyhhssyy-enhanced-1_3/main.py", line 7, in <module>
    from .stageModelEnhancement import download_penguin_stats_matrix,stage_model_enhancement_action
  File "/root/Amiya-Bot/plugins/amiyabot-arknights-hsyhhssyy-enhanced-1_3/stageModelEnhancement.py", line 21, in <module>
    from core import log, Message, Chain, tasks_control
ImportError: cannot import name 'tasks_control' from 'core' (/root/Amiya-Bot/core/__init__.py)

**Comment by hsyhhssyy** [comment]
1.5版已修复该问题
不过，这个插件现阶段还有啥意义吗？
官方已经支持paddle了好像，而且关卡查询也自带掉率了
